version: '3.1'

services:
  jwt-api:
    build:
      context: "."
      dockerfile: "./Dockerfile.native"
    environment:
      QUARKUS_DATASOURCE_JDBC_URL: jdbc:postgresql://jwt-db:5432/jwt-db
    restart: on-failure
    depends_on:
      - jwt-db
    ports:
      - 8080:8080

  jwt-db:
    image: postgres:latest
    hostname: jwt-db
    environment:
      - POSTGRES_PASSWORD=jwt
      - POSTGRES_USER=jwt
      - POSTGRES_DB=jwt-db
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://jwt-db:5432" ]
      interval: 2s
      timeout: 2s
      retries: 5
