@baseUrl = http://localhost:8080

# @name login
GET {{baseUrl}}/users/authenticate
Content-Type: application/json

@authToken = {{login.response.body.token}}

###
# @name info
GET {{baseUrl}}/movies/info HTTP/1.1
Authorization: Bearer {{authToken}}

###
GET {{baseUrl}}/movies/info2
Authorization: Bearer {{authToken}}

###
GET {{baseUrl}}/movies/all
Authorization: Bearer {{authToken}}

